name: "Hello World workflow"

on:
  push:
    branches:
      - main
      - master
      - production
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello world"
        run: echo "Hello, World"
 