name: "Multi Event Pipeline / workflow"

on:
  push:
    branches:
      - master
      - test
  workflow_dispatch:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "running on master push"
        run: echo "running on master push"
